import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Resume",
//   description: "Generated by create next app",
// };

const locales = ['en', 'pt'];

export default async function LocaleLayout({
  children, 
  params: { locale }
}: {
  children: React.ReactNode,
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider messages={messages}>
        {children}
        </NextIntlClientProvider>
        </body>
    </html>
  );
}